export const stateNames = {
  Tunisia: {
    Tunis: [
      "Tunis",
      "Le Bardo",
      "Le Kram",
      "	La Goulette",
      "Carthage",
      "Sidi Bou Said",
      "La Marsa",
      "Sidi Hassine",
    ],
    Ariana: [
      "Ariana",
      "La Soukra",
      "	Raoued",
      "Kalâat el-Andalous",
      "Sidi Thabet",
      "Ettadhamen-Mnihla",
    ],
    "Ben Arous": [
      "Ben Arous",
      "El Mourouj",
      "Hammam Lif",
      "Hammam Chott",
      "Bou Mhel el-Bassatine",
      "Ezzahra",
      "Radès",
      "Mégrine",
      "Mohamedia-Fouchana",
      "Mornag",
      "Khalidia",
    ],
    Manouba: [
      "Manouba",
      "Den Den",
      "Douar Hicher",
      "Oued Ellil",
      "Mornaguia",
      "Borj El Amri",
      "Djedeida",
      "Tebourba",
      "El Battan",
    ],
    Nabeul: [
      "Nabeul",
      "Dar Chaabane",
      "Béni Khiar",
      "El Maâmoura",
      "Somâa",
      "Korba",
      "Tazerka",
      "Menzel Temime",
      "Menzel Horr",
      "El Mida",
      "Kelibia",
      "Azmour",
      "Hammam Ghezèze",
      "Dar Allouch",
      "El Haouaria",
      "Takelsa",
      "Soliman",
      "Korbous",
      "Menzel Bouzelfa",
      "Béni Khalled",
      "Zaouiet Djedidi",
      "Grombalia",
      "Bou Argoub",
      "Hammamet",
    ],
    Zaghouan: [
      "Zaghouan",
      "Zriba",
      "Bir Mcherga",
      "Djebel Oust",
      "El Fahs",
      "Nadhour",
    ],
    Bizerte: [
      "Bizerte",
      "Sejnane",
      "Mateur",
      "Menzel Bourguiba",
      "Tinja",
      "Ghar al Milh",
      "Aousja",
      "Menzel Jemil",
      "Menzel Abderrahmane",
      "El Alia",
      "Ras Jebel",
      "Metline",
      "Raf Raf",
    ],
    Béja: [
      "Béja",
      "El Maâgoula",
      "Zahret Medien",
      "Nefza",
      "Téboursouk",
      "Testour",
      "Goubellat",
      "Majaz al Bab",
    ],
    Jendouba: [
      "Jendouba",
      "Bou Salem",
      "Tabarka",
      "Aïn Draham",
      "Fernana",
      "Beni MTir",
      "Ghardimaou",
      "Oued Melliz",
    ],
    Kef: [
      "El Kef",
      "Nebeur",
      "Touiref",
      "Sakiet Sidi Youssef",
      "Tajerouine",
      "Menzel Salem",
      "Kalaat es Senam",
      "Kalâat Khasba",
      "Jérissa",
      "El Ksour",
      "Dahmani",
      "Sers",
    ],
    Siliana: [
      "Siliana",
      "Bou Arada",
      "Gaâfour",
      "El Krib",
      "Sidi Bou Rouis",
      "Maktar",
      "Rouhia",
      "Kesra",
      "Bargou",
      "El Aroussa",
    ],
    Sousse: [
      "Ksibet Thrayet",
      "Ezzouhour",
      "Zaouiet Sousse",
      "Hammam Sousse",
      "Akouda",
      "Kalâa Kebira",
      "Sidi Bou Ali",
      "Hergla",
      "Enfidha",
      "Bouficha",
      "Sidi El Hani",
      "Msaken",
      "Kalâa Seghira",
      "Messaadine",
      "Kondar",
    ],
    Monastir: [
      "Monastir",
      "Khniss",
      "Ouerdanin",
      "Sahline Moôtmar",
      "Sidi Ameur",
      "Zéramdine",
      "Beni Hassen",
      "Ghenada",
      "Jemmal",
      "Menzel Kamel",
      "Zaouiet Kontoch",
      "Bembla-Mnara",
      "Menzel Ennour",
      "El Masdour",
      "Moknine",
      "Sidi Bennour",
      "Menzel Farsi",
      "Amiret El Fhoul",
      "Amiret Touazra",
      "Amiret El Hojjaj",
      "Cherahil",
      "Bekalta",
      "Téboulba",
      "Ksar Hellal",
      "Ksibet El Mediouni",
      "Benen Bodher",
      "Touza",
      "Sayada",
      "Lemta",
      "Bouhjar",
      "Menzel Hayet",
    ],
    Mahdia: [
      "Mahdia",
      "Rejiche",
      "Bou Merdes",
      "Ouled Chamekh",
      "Chorbane",
      "Hebira",
      "Essouassi",
      "El Djem",
      "Kerker",
      "Chebba",
      "Melloulèche",
      "Sidi Alouane",
      "Ksour Essef",
      "El Bradâa",
    ],
    Sfax: [
      "Sakiet Ezzit",
      "Chihia",
      "Sakiet Eddaïer",
      "Gremda",
      "El Ain",
      "Thyna",
      "Agareb",
      "Jebiniana",
      "El Hencha",
      "Menzel Chaker",
      "Ghraïba, Tunisia",
      "Bir Ali Ben Khélifa",
      "Skhira",
      "Mahares",
      "Kerkennah",
    ],
    Kairouan: [
      "Kairouan",
      "Chebika",
      "Sbikha",
      "Oueslatia",
      "Aïn Djeloula",
      "Haffouz",
      "Alaâ",
      "Hajeb El Ayoun",
      "Nasrallah",
      "Menzel Mehiri",
      "Echrarda",
      "Bou Hajla",
    ],
    Kasserine: [
      "Kasserine",
      "Sbeitla",
      "Sbiba",
      "Jedelienne",
      "Thala",
      "Haïdra",
      "Foussana",
      "Fériana",
      "Thélepte",
      "Magel Bel Abbès",
    ],
    "Sidi Bouzid": [
      "Sidi Bouzid",
      "Jilma",
      "Cebalet",
      "Bir El Hafey",
      "Sidi Ali Ben Aoun",
      "Menzel Bouzaiane",
      "Meknassy",
      "Mezzouna",
      "Regueb",
      "Ouled Haffouz",
    ],
    Gabès: [
      "Gabès",
      "Chenini Nahal",
      "Ghannouch",
      "Métouia",
      "Oudhref",
      "El Hamma",
      "Matmata",
      "Nouvelle Matmata",
      "Mareth",
      "Zarat",
    ],
    Medenine: [
      "Medenine",
      "Beni Khedache",
      "Ben Gardane",
      "Zarzis",
      "Houmt El Souk (Djerba)",
      "Midoun (Djerba)",
      "Ajim (Djerba)",
    ],
    Tataouine: ["Tataouine", "Bir Lahmar", "Ghomrassen", "Dehiba", "Remada"],
    Gafsa: [
      "Gafsa",
      "El Ksar",
      "Moularès",
      "Redeyef",
      "Métlaoui",
      "Mdhila",
      "El Guettar",
      "Sened",
    ],
    Tozeur: ["Tozeur", "Degache", "Hamet Jerid", "Nafta", "Tamerza"],
    Kebili: ["Kebili", "Djemna", "Douz", "El Golâa", "Souk Lahad"],
  },
};

export const mapboxTOKEN =
  "pk.eyJ1IjoibW9oYW1lZC1rYXJtb3VzIiwiYSI6ImNrbXoza2xhZDBhMDAyc3BmYXdsZzZ5bHYifQ.AOltPPAUduTvqaoDdx0jRw";
