# Generated by Django 3.0.5 on 2021-02-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='valide',
            field=models.BooleanField(),
        ),
    ]
