# Generated by Django 3.0.5 on 2021-03-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210303_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwrod',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
