# Generated by Django 3.0.5 on 2021-03-03 17:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210303_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountname', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.ImageField(default='C:/acounts/bibou/Desktop/projet/covid/pictures/patient/default.png', upload_to=api.models.upload_location_patient),
        ),
    ]
