# Generated by Django 3.0.5 on 2021-03-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210303_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountname',
            new_name='username',
        ),
    ]
