# Generated by Django 3.0.5 on 2021-03-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nom',
            field=models.EmailField(default='', max_length=30),
        ),
    ]
