# Generated by Django 3.0.5 on 2021-03-05 13:02

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_account_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.ImageField(default='./covid/pictures/patient/default.png', upload_to=api.models.upload_location_patient),
        ),
        migrations.CreateModel(
            name='patient_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='./covid/pictures/patient/default.png', upload_to=api.models.upload_location_patient)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_added')),
                ('validated', models.BooleanField(default=False)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
