# Generated by Django 3.0.5 on 2021-03-05 14:39

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210305_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='nom',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='prenom',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='patient_test',
            name='picture',
        ),
        migrations.AddField(
            model_name='account',
            name='account_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='./covid/pictures/default.png', force_format=None, keep_meta=True, quality=0, size=[300, 300], upload_to=api.models.upload_location_account),
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='tunis', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='governorate',
            field=models.CharField(default='tunis', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_picture',
            field=models.ImageField(default='./covid/pictures/default.png', upload_to=api.models.upload_location_patient),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], default='M', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_test',
            name='xray_image',
            field=models.ImageField(default='./covid/pictures/default.png', upload_to=api.models.upload_location_test),
        ),
        migrations.AlterField(
            model_name='patient_test',
            name='account',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
