# Generated by Django 3.0.5 on 2021-03-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210305_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_picture',
        ),
    ]
