# Generated by Django 3.0.5 on 2021-03-08 18:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_account_account_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_picture',
            field=models.ImageField(default='./covid/pictures/default.png', upload_to=api.models.upload_location_patient, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='date_added'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_picture',
            field=models.ImageField(default='./covid/pictures/default.png', upload_to=api.models.upload_location_patient, verbose_name=''),
        ),
    ]
