# Generated by Django 3.0.5 on 2021-03-10 18:43

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210308_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_picture',
            field=models.ImageField(default='./frontend/public/pictures/account/default.png', upload_to=api.models.upload_location_account, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_picture',
            field=models.ImageField(default='./covid/frontend/pictures/account/default.png', upload_to=api.models.upload_location_patient, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient_test',
            name='xray_image',
            field=models.ImageField(default='./covid/frontend/pictures/account/default.png', upload_to=api.models.upload_location_test),
        ),
    ]
