# Generated by Django 3.0.5 on 2021-03-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_updated',
        ),
    ]
