# Generated by Django 3.0.5 on 2021-03-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_patient_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='covid19',
            field=models.BooleanField(default=False),
        ),
    ]
