# Generated by Django 3.0.5 on 2021-03-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_patient_covid19'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='covid19',
            field=models.CharField(max_length=30),
        ),
    ]
