# Generated by Django 3.0.5 on 2021-03-17 15:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210311_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_picture',
            field=models.ImageField(default='./frontend/public/pictures/account/default.png', upload_to=api.models.upload_location_patient, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='patient_test',
            name='xray_image',
            field=models.ImageField(default='./frontend/public/pictures/account/default.png', upload_to=api.models.upload_location_test),
        ),
    ]
