# Generated by Django 3.0.5 on 2021-03-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_patient_test_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_test',
            name='date_added',
            field=models.DateField(auto_now=True, verbose_name='date_added'),
        ),
    ]
