# Generated by Django 3.0.5 on 2021-04-11 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210403_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cough', models.CharField(default='false', max_length=30)),
                ('fever', models.CharField(default='false', max_length=30)),
                ('sore_throat', models.CharField(default='false', max_length=30)),
                ('shortness_of_breath', models.CharField(default='false', max_length=30)),
                ('head_ache', models.CharField(default='false', max_length=30)),
                ('gender', models.CharField(default='false', max_length=30)),
                ('date_added', models.DateField(auto_now=True, verbose_name='date_added')),
                ('validated', models.BooleanField(default=False)),
                ('result', models.CharField(default='', max_length=30)),
                ('account', models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
